spring.h2.console.enabled=false
spring.batch.jdbc.initialize-schema=always
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.batch.job.enabled=true
app.batch.default-input-file=classpath:data/transactions.csv
